# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('travel_start', models.DateTimeField(default='9999-11-29')),
                ('travel_end', models.DateTimeField(default='9999-11-29')),
                ('plan', models.ManyToManyField(related_name='user_plan', to='logReg.User')),
            ],
        ),
    ]
