# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0002_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_end',
            field=models.DateTimeField(blank=True, default='9999-11-29', null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_start',
            field=models.DateTimeField(blank=True, default='9999-11-29', null=True),
        ),
    ]
