# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0007_auto_20170227_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='travel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='the_travel',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='the_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.DeleteModel(
            name='TravelPlan',
        ),
        migrations.AddField(
            model_name='poke',
            name='pokee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='was_poked', to='logReg.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='did_poke', to='logReg.User'),
        ),
    ]
