# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0008_auto_20170228_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateTimeField(),
        ),
    ]
