# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0009_auto_20170302_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=100)),
                ('author', models.CharField(max_length=45)),
                ('poke_count', models.IntegerField(blank=True, null=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_post', to='logReg.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='poke',
            name='pokee',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
        migrations.AddField(
            model_name='favorite',
            name='quote_fave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logReg.Quote'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_fav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logReg.User'),
        ),
    ]
