# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0010_auto_20170302_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='quote_fave',
            new_name='quote_fav',
        ),
    ]
