# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0011_auto_20170302_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quote_fav',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user_fav',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='poke_count',
        ),
        migrations.AddField(
            model_name='favorite',
            name='fav_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_fav', to='logReg.Quote'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='fav_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fave', to='logReg.User'),
        ),
    ]
