# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0012_auto_20170302_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='fav_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fav', to='logReg.User'),
        ),
    ]
